src/Entity/Reclamation.php
<?php

namespace App\Entity;

use App\Repository\ReclamationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Serializer\Annotation\Ignore;

#[ORM\Entity(repositoryClass: ReclamationRepository::class)]
class Reclamation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(nullable: true)]
    private ?int $type_reclamation_id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $nom_client = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $prenom = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $tel = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $adresse = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $email = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $etat = null;

    #[ORM\ManyToOne(inversedBy: 'reclamations')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Typereclamation $Typereclamation = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTypereclamationId(): ?int
    {
        return $this->type_reclamation_id;
    }

    public function setTypereclamationId(?int $type_reclamation_id): self
    {
        $this->type_reclamation_id = $type_reclamation_id;

        return $this;
    }

    public function getNomClient(): ?string
    {
        return $this->nom_client;
    }

    public function setNomClient(?string $nom_client): self
    {
        $this->nom_client = $nom_client;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(?string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getTel(): ?string
    {
        return $this->tel;
    }

    public function setTel(?string $tel): self
    {
        $this->tel = $tel;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(?string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getEtat(): ?string
    {
        return $this->etat;
    }

    public function setEtat(?string $etat): self
    {
        $this->etat = $etat;

        return $this;
    }
    public function getTypereclamation(): ?Typereclamation
    {
        return $this->Typereclamation;
    }

    public function setTypereclamation(?Typereclamation $Typereclamation): self
    {
        $this->Typereclamation = $Typereclamation;

        return $this;
    }
    
}

src/Form/ReclamationType.php
<?php

namespace App\Form;

use App\Entity\Reclamation;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ReclamationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Typereclamation')
            ->add('NomClient')
            ->add('Prenom')
            ->add('Tel')
            ->add('adresse')
            ->add('Email')
            ->add('Description')
            ->add('Etat')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Reclamation::class,
        ]);
    }
}

src/Controller/ReclamationController.php
<?php

namespace App\Controller;

use App\Entity\Reclamation;
use App\Form\ReclamationType;
use App\Repository\ReclamationRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\VarDumper\VarDumper;
use App\Form\SearchCType;
use Dompdf\Options;
use Dompdf\Dompdf;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;
use Knp\Bundle\PaginatorBundle\Twig\Extension\PaginationExtension;
use Knp\Bundle\PaginatorBundle\Pagination\SlidingPaginationInterface;
use Doctrine\ORM\EntityManagerInterface;


#[Route('/reclamation', methods: ['GET', 'POST'])]
class ReclamationController extends AbstractController
{   #[Route('/stats',name:'app_reclamation_stat')]
    public function stats(ReclamationRepository $repository,NormalizerInterface $Normalizer)
    {
        $reclamations=$repository->countByDate();
        $dates=[];
        $reclamationsCount=[];
        foreach($reclamations as $reclamation){
            $dates[] = $reclamation['datereclamation'];
            $reclamationsCount[] = $reclamation['count'];
        }
        dump($reclamationsCount);
        return $this->render('reclamation/stats.html.twig',[
            'dates' => json_encode($dates),
            'reclamationsCount' => json_encode($reclamationsCount),

        ]);
    }

    #[Route('/', name: 'app_reclamation_index', methods: ['GET'])]
    public function index(ReclamationRepository $reclamationRepository,Request $request,PaginatorInterface $paginator): Response
    {
        $query = $request->query->get('q');
        $reclamations=$reclamationRepository->findAll(); 
        $pagination = $paginator->paginate($reclamations,$request->query->getInt('page',1),2);
        $formSearch= $this->createForm(SearchCType::class); 
    $formSearch->handleRequest($request);
      if($formSearch->isSubmitted()){
        $nom= $formSearch->get('NomClient')->getData();
        $result= $reclamationRepository->search($nom);     // recherche
        return $this->renderForm('admin/Reclamation.html.twig',
            array('reclamations'=>$result,
              
                "searchForm"=>$formSearch));
                
    }
   
 return $this->renderForm('admin/Reclamation.html.twig', [
     'reclamations' => $pagination,  "searchForm"=>$formSearch]);

    
    {
        return $this->render('reclamation/listp.html.twig', [
            'reclamations' => $reclamationRepository->findAll(),
        ]);
    }
}

#[Route('/trie', name: 'trie' )]
public function trie(ReclamationRepository $reclamationRepository ,Request $request,PaginatorInterface $paginator)
{
    $query = $request->query->get('q');
    $reclamations=$reclamationRepository->Triepardate(); 
    $pagination = $paginator->paginate($reclamations,$request->query->getInt('page',1),2);
    $formSearch= $this->createForm(SearchCType::class); 
$formSearch->handleRequest($request);
  if($formSearch->isSubmitted()){
    $nom= $formSearch->get('NomClient')->getData();
    $result= $reclamationRepository->search($nom);     // recherche
    return $this->renderForm('admin/Reclamation.html.twig',
        array('reclamations'=>$result,
          
            "searchForm"=>$formSearch));
            
}

return $this->renderForm('admin/Reclamation.html.twig', [
 'reclamations' => $pagination,  "searchForm"=>$formSearch
]);


{
    return $this->render('admin/Reclamation.html.twig', [
        'reclamations' => $reclamationRepository->findAll(),
    ]);
}
}
#[Route('/calendar', name: 'app_calendar')]
public function index2(ReclamationRepository $repository): Response
{
    $activiters= $repository->findAll();
    $emploit=[];
    foreach ($activiters as $activ){
        $emploit[]=[
            'id'=>$activ->getId(),
            'title'=> $activ->getNomClient(),
            'description'=> $activ->$this->getDescription()(),
            'etat'=> $activ->getEtat(),
            'backgroundColor'=>$this->getRandomColor()
        ];
    }
    $data=json_encode($emploit);




    return $this->render('calendar/Calendar.html.twig',array("data"=>$data));
}


public function generateICalendarFile(ReclamationRepository $repository)
{
    
    $activiters = $repository->findAll();

    $ics = "BEGIN:VCALENDAR\r\nVERSION:2.0\r\n";
    $i=0;
    foreach ($activiters as $activ)
    {
        $i=$i+1;
        $id = $activ->getId();
        $titre = $activ->getNomClient();
        $description = $activ->$this->getDescription()();
        $etat = $activ->getEtat();
        $ics .= "Activiter num :".$i."\r\n";
        $ics .= "Description:" . $description . "\r\n";
        $ics .= "Etat:" . $etat . "\r\n";
        $ics .= "UID:" . $id . "\r\n";
        $ics .= "SUMMARY:" . $titre . "\r\n";
        $ics .= "END:VEVENT\r\n";
    }


    $response = new Response($ics);
    $response->headers->set('bienvenue', 'Calendrier');


    return $response;
}


public function downloadCalendar(ReclamationRepository $repository)
{
    $response = $this->generateICalendarFile($repository);

    return $response;
}




private function getRandomColor()
{
    // Generate random values for the red, green, and blue components
    $r = mt_rand(100, 255);
    $g = mt_rand(100, 255);
    $b = mt_rand(100, 255);

    // Combine the red, green, and blue components into a hexadecimal color string
    $color = "#" . dechex($r) . dechex($g) . dechex($b);

    return $color;
}
    #[Route('/new', name: 'app_reclamation_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ReclamationRepository $reclamationRepository): Response
    {
        $reclamation = new Reclamation();
        $form = $this->createForm(ReclamationType::class, $reclamation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $reclamationRepository->save($reclamation, true);

            return $this->redirectToRoute('app_reclamation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('reclamation/new.html.twig', [
            'reclamation' => $reclamation,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_reclamation_show', methods: ['GET'])]
    public function show(Reclamation $reclamation): Response
    {
        return $this->render('reclamation/show.html.twig', [
            'reclamation' => $reclamation,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_reclamation_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Reclamation $reclamation, ReclamationRepository $reclamationRepository): Response
    {
        $form = $this->createForm(ReclamationType::class, $reclamation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $reclamationRepository->save($reclamation, true);

            return $this->redirectToRoute('app_reclamation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('reclamation/edit.html.twig', [
            'reclamation' => $reclamation,
            'form' => $form,
        ]);
    }
    public function remove(Reclamation $reclamation, bool $flush = false)
    {
    $this->_em->remove($reclamation);
    if ($flush) {
        $this->_em->flush();
    }
    }
    #[Route('/{id}', name: 'app_reclamation_delete', methods: ['POST'])]
    public function delete(Request $request, Reclamation $reclamation, ReclamationRepository $reclamationRepository , EntityManagerInterface $entityManager ): Response
    {
        if ($this->isCsrfTokenValid('delete'.$reclamation->getId(), $request->request->get('_token'))) {
            $entityManager->remove($reclamation, true);
            $entityManager->flush();
        }
        dump($reclamation);


        return $this->redirectToRoute('app_reclamation_index', [], Response::HTTP_SEE_OTHER);
    }
    #[Route('/reclamation/data/download', name: 'users_data_download')]

    public function usersDataDownload(ReclamationRepository $reclamation)
    {
        // On définit les options du PDF
        $pdfOptions = new Options();
        // Police par défaut
        $pdfOptions->set('defaultFont', 'Arial');
        $pdfOptions->setIsRemoteEnabled(true);
    
        // On instancie Dompdf
        $dompdf = new Dompdf($pdfOptions);
        $reclamation= $reclamation->findAll();
       
        // $classrooms= $this->getDoctrine()->getRepository(classroomRepository::class)->findAll();
    
        $context = stream_context_create([
            'ssl' => [
                'verify_peer' => FALSE,
                'verify_peer_name' => FALSE,
                'allow_self_signed' => TRUE
            ]
        ]);
        $dompdf->setHttpContext($context);
    
        // On génère le html
        $html =$this->renderView('reclamation/listp.html.twig',[
            'reclamations'=>$reclamation
        ]);
    
        $dompdf->loadHtml($html);
        $dompdf->setPaper('A4', 'portrait');
        $dompdf->render();
    
        // On génère un nom de fichier
        $fichier = 'Liste-reclamation' .'.pdf';
    
        // On envoie le PDF au navigateur
        $dompdf->stream($fichier, [
            'Attachment' => true
        ]);
    
        return new Response() ;
    }

}

templates/reclamation/_delete_form.html.twig
{% extends 'admin/Base.html.twig'%}

{% block body %}
<form method="post" action="{{ path('app_reclamation_delete', {'id': reclamation.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ reclamation.id) }}">
    <button class="btn">Delete</button>
</form>
{% endblock %}

templates/reclamation/_form.html.twig
{% extends 'client/Base.html.twig' %}

{% block body %}

{# {{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }} #}




    {{ form_start(form,{'attr': {'novalidate': 'novalidate'}})}}
    <div class="quform-elements">
        
                    <div class="row mb-3">
                        <div>{{form_label(form.NomClient,"NomClient",{'attr':{'class':'col-sm-2 col-form-label'}})}} <span class="quform-required"> *</span></div>
                        <div class="col-sm-10">
                            {{ form_widget(form.NomClient,{'attr':{'class':'form-control'}}) }}
                            {{ form_errors(form.NomClient,{'attr':{'class':'text-danger'}})}}
                        </div>
                    </div>
                     <div class="row mb-3">
                        <div>{{form_label(form.Prenom,"Prenom",{'attr':{'class':'col-sm-2 col-form-label'}})}} <span class="quform-required"> *</span></div>
                        <div class="col-sm-10">
                            {{ form_widget(form.Prenom,{'attr':{'class':'form-control'}}) }}
                            {{ form_errors(form.Prenom,{'attr':{'class':'text-danger'}})}}
                        </div>
                          <div class="row mb-3">
                        <div>{{form_label(form.Tel,"Tel",{'attr':{'class':'col-sm-2 col-form-label'}})}} <span class="quform-required"> *</span></div>
                        <div class="col-sm-10">
                            {{ form_widget(form.Tel,{'attr':{'class':'form-control'}}) }}
                            {{ form_errors(form.Tel,{'attr':{'class':'text-danger'}})}}
                        </div>
                           <div class="row mb-3">
                        <div>{{form_label(form.adresse,"adresse",{'attr':{'class':'col-sm-2 col-form-label'}})}} <span class="quform-required"> *</span></div>
                        <div class="col-sm-10">
                            {{ form_widget(form.adresse,{'attr':{'class':'form-control'}}) }}
                            {{ form_errors(form.adresse,{'attr':{'class':'text-danger'}})}}
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div>{{form_label(form.Email,"Email",{'attr':{'class':'col-sm-2 col-form-label'}})}} <span class="quform-required"> *</span></div>
                        <div class="col-sm-10">
                            {{ form_widget(form.Email,{'attr':{'class':'form-control'}}) }}
                            {{ form_errors(form.Email,{'attr':{'class':'text-danger'}})}}
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div>{{form_label(form.Description,"Description",{'attr':{'class':'col-sm-2 col-form-label'}})}} <span class="quform-required"> *</span></div>
                        <div class="col-sm-10">
                            {{ form_widget(form.Description,{'attr':{'class':'form-control'}}) }}
                            {{ form_errors(form.Description,{'attr':{'class':'text-danger'}})}}
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div>{{form_label(form.Etat,"Etat",{'attr':{'class':'col-sm-2 col-form-label'}})}} <span class="quform-required"> *</span></div>
                        <div class="col-sm-10">
                            {{ form_widget(form.Etat,{'attr':{'class':'form-control'}}) }}
                            {{ form_errors(form.Etat,{'attr':{'class':'text-danger'}})}}
                        </div>
                    </div>
                  


                    
                    <div class="row mb-3">
                        <div>{{form_label(form.Typereclamation,"Typereclamation",{'attr':{'class':'col-sm-2 col-form-label'}})}} <span class="quform-required"> *</span></div>
                        <div class="col-sm-10">
                            {{ form_widget(form.Typereclamation,{'attr':{'class':'form-select'}}) }}
                            {{ form_errors(form.Typereclamation,{'attr':{'class':'text-danger'}})}}
                        </div>
                    </div>

                    </div>
                    <div class="row mb-3">
                    <div class="col-sm-10">
                        <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
                        
                    </div>
                    </div>

                {{ form_end(form) }}


            </div>
          </div>




</div>
{% endblock %}

templates/reclamation/edit.html.twig
{% extends 'admin/Base.html.twig'%}

{% block title %}Modifier reclamation {% endblock %}
{% block body %}

<div class="" style='margin-left: 20% ;'>
    <div class="pagetitle">
      <h1>Nouveau reclamation</h1>
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="index.html">Accueil</a></li>
          <li class="breadcrumb-item">reclamation</li>
          <li class="breadcrumb-item active">Nouvaeu reclamation</li>
        </ol>
      </nav>
    </div><!-- End Page Title -->
     <div class="card">
            <div class="card-body">
              <h5 class="card-title">Modifier reclamation</h5>

              <!-- Modifier reclamation -->
                {{ form_start(form,{'attr': {'novalidate': 'novalidate'}})}}
                  <div class="quform-elements">
                   <div class="row mb-3">
                        <div>{{form_label(form.NomClient,"NomClient",{'attr':{'class':'col-sm-2 col-form-label'}})}} <span class="quform-required"> *</span></div>
                        <div class="col-sm-10">
                            {{ form_widget(form.NomClient,{'attr':{'class':'form-control'}}) }}
                            {{ form_errors(form.NomClient,{'attr':{'class':'text-danger'}})}}
                        </div>
                    </div>
                     <div class="row mb-3">
                        <div>{{form_label(form.Prenom,"Prenom",{'attr':{'class':'col-sm-2 col-form-label'}})}} <span class="quform-required"> *</span></div>
                        <div class="col-sm-10">
                            {{ form_widget(form.Prenom,{'attr':{'class':'form-control'}}) }}
                            {{ form_errors(form.Prenom,{'attr':{'class':'text-danger'}})}}
                        </div>
                          <div class="row mb-3">
                        <div>{{form_label(form.Tel,"Tel",{'attr':{'class':'col-sm-2 col-form-label'}})}} <span class="quform-required"> *</span></div>
                        <div class="col-sm-10">
                            {{ form_widget(form.Tel,{'attr':{'class':'form-control'}}) }}
                            {{ form_errors(form.Tel,{'attr':{'class':'text-danger'}})}}
                        </div>
                           <div class="row mb-3">
                        <div>{{form_label(form.adresse,"adresse",{'attr':{'class':'col-sm-2 col-form-label'}})}} <span class="quform-required"> *</span></div>
                        <div class="col-sm-10">
                            {{ form_widget(form.adresse,{'attr':{'class':'form-control'}}) }}
                            {{ form_errors(form.adresse,{'attr':{'class':'text-danger'}})}}
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div>{{form_label(form.Email,"Email",{'attr':{'class':'col-sm-2 col-form-label'}})}} <span class="quform-required"> *</span></div>
                        <div class="col-sm-10">
                            {{ form_widget(form.Email,{'attr':{'class':'form-control'}}) }}
                            {{ form_errors(form.Email,{'attr':{'class':'text-danger'}})}}
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div>{{form_label(form.Description,"Datededebut",{'attr':{'class':'col-sm-2 col-form-label'}})}} <span class="quform-required"> *</span></div>
                        <div class="col-sm-10">
                            {{ form_widget(form.Description,{'attr':{'class':'form-control'}}) }}
                            {{ form_errors(form.Description,{'attr':{'class':'text-danger'}})}}
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div>{{form_label(form.Etat,"Etat",{'attr':{'class':'col-sm-2 col-form-label'}})}} <span class="quform-required"> *</span></div>
                        <div class="col-sm-10">
                            {{ form_widget(form.Etat,{'attr':{'class':'form-control'}}) }}
                            {{ form_errors(form.Etat,{'attr':{'class':'text-danger'}})}}
                        </div>
                    </div>
                  


                    
                    <div class="row mb-3">
                        <div>{{form_label(form.Typereclamation,"Typereclamation",{'attr':{'class':'col-sm-2 col-form-label'}})}} <span class="quform-required"> *</span></div>
                        <div class="col-sm-10">
                            {{ form_widget(form.Typereclamation,{'attr':{'class':'form-select'}}) }}
                            {{ form_errors(form.Typereclamation,{'attr':{'class':'text-danger'}})}}
                        </div>
                    </div>
   <div class="row mb-3">
                    <div class="col-sm-10">
                        <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
                    </div>
                    </div>
                    </div>

                {{ form_end(form) }}


            </div>
          </div>

{% endblock %}

templates/reclamation/index.html.twig
<!DOCTYPE html>

<title>Reclamation index</title>

{% block body %}
    <h1>Reclamation index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Type_reclamation_id</th>
                <th>Nom_client</th>
                <th>Prenom</th>
                <th>Tel</th>
                <th>Adresse</th>
                <th>Email</th>
                <th>Description</th>
                <th>Etat</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for reclamation in reclamations %}
            <tr>
                <td>{{ reclamation.id }}</td>
                <td>{{ reclamation.typereclamationId }}</td>
                <td>{{ reclamation.NomClient }}</td>
                <td>{{ reclamation.Prenom }}</td>
                <td>{{ reclamation.Tel }}</td>
                <td>{{ reclamation.adresse }}</td>
                <td>{{ reclamation.Email }}</td>
                <td>{{ reclamation.Description }}</td>
                <td>{{ reclamation.Etat }}</td>
                <td>
                    <a href="{{ path('app_reclamation_show', {'id': reclamation.id}) }}">show</a>
                    <a href="{{ path('app_reclamation_edit', {'id': reclamation.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_reclamation_new') }}">Create new</a>
{% endblock %}

templates/reclamation/new.html.twig
<!DOCTYPE html>

<title>New Reclamation</title>

{% block body %}
    <h1>Create new Reclamation</h1>

    {{ include('reclamation/_form.html.twig') }}

    <a href="{{ path('app_reclamation_index') }}">back to list</a>
    

{% endblock %}

templates/reclamation/show.html.twig
<!DOCTYPE html>

<title>Reclamation</title>

{% block body %}
    <h1>Reclamation</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ reclamation.id }}</td>
            </tr>
            <tr>
                <th>Type_reclamation_id</th>
                <td>{{ reclamation.typereclamationId }}</td>
            </tr>
            <tr>
                <th>Nom_client</th>
                <td>{{ reclamation.NomClient }}</td>
            </tr>
            <tr>
                <th>Prenom</th>
                <td>{{ reclamation.Prenom }}</td>
            </tr>
            <tr>
                <th>Tel</th>
                <td>{{ reclamation.Tel }}</td>
            </tr>
            <tr>
                <th>Adresse</th>
                <td>{{ reclamation.adresse }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ reclamation.Email }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ reclamation.Description }}</td>
            </tr>
            <tr>
                <th>Etat</th>
                <td>{{ reclamation.Etat }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_reclamation_index') }}">back to list</a>

    <a href="{{ path('app_reclamation_edit', {'id': reclamation.id}) }}">edit</a>

    {{ include('reclamation/_delete_form.html.twig') }}
{% endblock %}

templates/reclamation/stats.html.twig
{%extends 'admin/Base.html.twig'%}

{% block title %}
    Gestion des Reclamations
{% endblock %}
{% block body %}
<main class="main-content position-relative max-height-vh-100 h-100 border-radius-lg "  style='margin-left: 20% ;'>

    <div class="container-fluid py-4">
        <div class="row" style="display: flex;align-items: center;justify-content: center;margin-top: 150px;">
        <div class="col-12">
          <div class="card my-4">
            <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
              <div class="bg-gradient-primary shadow-primary border-radius-lg pt-4 pb-3">
                <h6 class="text-white text-capitalize ps-3">Table des reclamations </h6>
                 
              </div>
            </div>
            <div class="card-body px-0 pb-2">
              <div class="table-responsive p-0">
    <canvas id="reclamations" class="charts" width="400" height="150"></canvas>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js" integrity="sha512-s+xg36jbIujB2S2VKfpGmlC3T5V2TF3lY48DX7u2r9XzGzgPsa6wTpOQA7J9iffvdeBN0q9tKzRxVxw1JviZPg==" crossorigin="anonymous"></script>
    <script>
        let reclamations = document.querySelector("#reclamations")
        let recGraph = new Chart(reclamations, {
            type: "bar",
            data: {

                labels: {{ dates|raw }},
                datasets: [{
                    label: "Nombre de reclamations",
                    data: {{ reclamationsCount|raw }},
                    backgroundColor: '#0f730b',

                }]
            },
            options: {
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero: true
                        }
                    }]
                }
            }
        })
    </script>

{% endblock %}